const SCREENS = {
  HOME_SCREEN: "HOME_SCREEN",
  ABOUT_SCREEN: "ABOUT_SCREEN",
  FILTER_SCREEN: "FILTER_SCREEN",
  ADD_TODO_SCREEN: "ADD_TODO_SCREEN",
  INTRO_SCREEN: "INTRO_SCREEN",
};

export default SCREENS;
